apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: azurefunctionsroutes
spec:
  http:
  - name: all
    match:
      hosts:
      - local.functions.all
      paths:
      - "/*"
    backends:
    - serviceName: functionapp-service
      servicePort: 80
  - name: param
    match:
      hosts:
      - local.functions.params
      paths:
      - "/apisixdemo/getweather/getweatherwithmultiparam"
    backends:
    - serviceName: functionapp-service
      servicePort: 80